repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/ikamensh/flynt/
    rev: '0.69'
    hooks:
      - id: flynt
        language: python
        types: [python]
        args: [--line-length, '999', --aggressive, --fail-on-change]
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        language_version: python3.6
# Temp until https://github.com/flakehell/flakehell/pull/23 merged
  - repo: https://github.com/mcarans/flakehell
    rev: v.0.8.0
    hooks:
      - id: flakehell
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.4.0
    hooks:
      - id: pip-compile
        name: pip-compile requirements/dev.in
        args: [requirements/dev.in, -o, requirements/dev.txt]
        files: ^requirements[/]dev\.in$
        stages: [push]
      - id: pip-compile
        name: pip-compile requirements/runtime.in
        args: [requirements/runtime.in, -o, requirements/runtime.txt]
        files: ^requirements[/]runtime\.in$
        stages: [push]
      - id: pip-compile
        name: pip-compile requirements/style.in
        args: [requirements/style.in, -o, requirements/style.txt]
        files: ^requirements[/]style\.in$
        stages: [push]
      - id: pip-compile
        name: pip-compile requirements/typing.in
        args: [requirements/typing.in, -o, requirements/typing.txt]
        files: ^requirements[/]typing\.in$
        stages: [push]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
