repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
# Temp until https://github.com/flakehell/flakehell/pull/23 merged
  - repo: https://github.com/mcarans/flakehell
    rev: 1b84f4dd6c16232b5c0c6206511427676ab55f5b
    hooks:
      - id: flakehell
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
