default_language_version:
    python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-ast
      - id: check-docstring-first
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/ikamensh/flynt/
    rev: '0.69'
    hooks:
      - id: flynt
        language: python
        types: [python]
        args: [--line-length, '999', --aggressive, --fail-on-change]
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        language_version: python3.6
# Temp until https://github.com/flakehell/flakehell/pull/23 merged
  - repo: https://github.com/mcarans/flakehell
    rev: 1b84f4dd6c16232b5c0c6206511427676ab55f5b
    hooks:
      - id: flakehell
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
